
main: sequensial parallel

sequensial:
	g++ -fopenmp producer-consumer.cpp -o producer-consumer

parallel:
	g++ -fopenmp producer-consumer-parallel.cpp -o producer-consumer-parallel

tests:
	./producer-consumer 1 1 15

test:
